### ISSUE TITLE
The number of linear regions always equals batch_size*sample_batch ?

### ISSUE THREAD

**Issue by TheSunWillRise** [VITA-Group/TEGNAS#5]
I have used your code to test the number of linear regions of several existing models, such as ResNet18, ResNet50, ResNet101, and so on. I find the resulting number of linear regions always equals batch_size*sample_batch. 
Is this normal? If it is normal, I wonder whether the measurement of linear region numbers is meaningful.

**Comment by chenwydj** [comment]
Hi @815961618,

Thanks for your interest in our work!

Your observation is reasonable. In other words, what you observed indicates that every single input sample is allocated to a unique local linear region (thus #linear region == batch_size*sample_batch).

The reason is: linear regions of deep CNNs are huge. Every element (pixel) in the learned features is an activation, and we need to summarize the number of unique activations from all these elements. This means the theoretical upper bound of #linear regions is quadratic to the input height (or width) and linear to the number of input channel.

For ResNet models of over 10 millions of parameters, you will need a much larger number of input samples (i.e. higher computation cost) to distinguish different CNN architectures in terms of their #linear regions; otherwise it will be very likely that every single input sample will locate in a unique linear region, making different CNNs of seemly equal expressivity.
